//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatIt_.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeatIt_.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In this challenge you have to run faster than 20 km/h for 30 seconds..
        /// </summary>
        public static string Challenge1_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge1_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Challenge1_DescriptionTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_DescriptionTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Challenge1_DetailsTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_DetailsTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration:.
        /// </summary>
        public static string Challenge1_DurationTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_DurationTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed (km/h).
        /// </summary>
        public static string Challenge1_SpeedTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_SpeedTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start running!.
        /// </summary>
        public static string Challenge1_StartButton {
            get {
                return ResourceManager.GetString("Challenge1_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Time:.
        /// </summary>
        public static string Challenge1_StartTimeTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_StartTimeTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Left (s).
        /// </summary>
        public static string Challenge1_TimeLeftTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_TimeLeftTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To Beat:.
        /// </summary>
        public static string Challenge1_ToBeatTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_ToBeatTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en este desafio tienes que agitar el celular cuando piense que el timer finalizo..
        /// </summary>
        public static string Challenge2_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge2_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start!.
        /// </summary>
        public static string Challenge2_StartButton {
            get {
                return ResourceManager.GetString("Challenge2_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In this challenge you have to .....
        /// </summary>
        public static string Challenge4_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge4_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play Sound.
        /// </summary>
        public static string Challenge4_PlaySoundButton {
            get {
                return ResourceManager.GetString("Challenge4_PlaySoundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Challenges.
        /// </summary>
        public static string HomePage_ChallengesPivotTitle {
            get {
                return ResourceManager.GetString("HomePage_ChallengesPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string HomePage_LogoutBtnTitle {
            get {
                return ResourceManager.GetString("HomePage_LogoutBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string HomePage_ProfilePivotTitle {
            get {
                return ResourceManager.GetString("HomePage_ProfilePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking.
        /// </summary>
        public static string HomePage_RankingPivotTitle {
            get {
                return ResourceManager.GetString("HomePage_RankingPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        public static string HomePage_SettingsTxtBlockTitle {
            get {
                return ResourceManager.GetString("HomePage_SettingsTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login with Facebook.
        /// </summary>
        public static string LoginPage_LoginBtnTitle {
            get {
                return ResourceManager.GetString("LoginPage_LoginBtnTitle", resourceCulture);
            }
        }
    }
}
