//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatIt_.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeatIt_.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Challenge_Days {
            get {
                return ResourceManager.GetString("Challenge_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Challenge_Hours {
            get {
                return ResourceManager.GetString("Challenge_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than A Minute!.
        /// </summary>
        public static string Challenge_LessMinutes {
            get {
                return ResourceManager.GetString("Challenge_LessMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Challenge_Minutes {
            get {
                return ResourceManager.GetString("Challenge_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump the gray ball as much as possible !.
        /// </summary>
        public static string Challenge1_Description {
            get {
                return ResourceManager.GetString("Challenge1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to run faster than 15 km/h for 45 seconds..
        /// </summary>
        public static string Challenge1_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge1_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to run faster than 10 km/h for 30 seconds..
        /// </summary>
        public static string Challenge1_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge1_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Challenge1_DescriptionTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_DescriptionTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Challenge1_DetailsTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_DetailsTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Challenge1_DurationTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_DurationTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge not Completed..
        /// </summary>
        public static string Challenge1_Loss {
            get {
                return ResourceManager.GetString("Challenge1_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Slow Down to Begin The Challenge!.
        /// </summary>
        public static string Challenge1_ReduceSpeed {
            get {
                return ResourceManager.GetString("Challenge1_ReduceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (km/h).
        /// </summary>
        public static string Challenge1_SpeedTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_SpeedTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start running!.
        /// </summary>
        public static string Challenge1_StartButton {
            get {
                return ResourceManager.GetString("Challenge1_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string Challenge1_StartTimeTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_StartTimeTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Left (s).
        /// </summary>
        public static string Challenge1_TimeLeftTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_TimeLeftTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usain Bolt.
        /// </summary>
        public static string Challenge1_Title {
            get {
                return ResourceManager.GetString("Challenge1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Beat:.
        /// </summary>
        public static string Challenge1_ToBeatTxtBlockTitle {
            get {
                return ResourceManager.GetString("Challenge1_ToBeatTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Completed!.
        /// </summary>
        public static string Challenge1_Win {
            get {
                return ResourceManager.GetString("Challenge1_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to shake your cellphone when you think the timer reachs 0, the timer will hide 4 times so pay attention..
        /// </summary>
        public static string Challenge2_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge2_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to shake your cellphone when you think the timer reachs 0, the timer will hide 3 times so pay attention..
        /// </summary>
        public static string Challenge2_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge2_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        public static string Challenge2_StartButton {
            get {
                return ResourceManager.GetString("Challenge2_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake Me Up!.
        /// </summary>
        public static string Challenge2_Title {
            get {
                return ResourceManager.GetString("Challenge2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to challenge.
        /// </summary>
        public static string Challenge3_BackButton {
            get {
                return ResourceManager.GetString("Challenge3_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete publication form wall .
        /// </summary>
        public static string Challenge3_Delete {
            get {
                return ResourceManager.GetString("Challenge3_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to invite your friends using facebook or SMS, minimum four sms and the post on your wall. Remember more friends more score!.
        /// </summary>
        public static string Challenge3_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge3_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to invite your fiends using facebook or SMS, minimum two sms and the post on your wall. Remember more friends more score!.
        /// </summary>
        public static string Challenge3_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge3_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Challenge3_Done {
            get {
                return ResourceManager.GetString("Challenge3_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try BeatIt! 
        ///Windows: http://www.windowsphone.com/en-us/store/app/beatit/66fa9546-f6ae-4a10-8acb-91472ac3ff96
        ///Also available for Android!.
        /// </summary>
        public static string Challenge3_Message {
            get {
                return ResourceManager.GetString("Challenge3_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Posted successfully.
        /// </summary>
        public static string Challenge3_MessagePosted {
            get {
                return ResourceManager.GetString("Challenge3_MessagePosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New High Score!.
        /// </summary>
        public static string Challenge3_NewHighScore {
            get {
                return ResourceManager.GetString("Challenge3_NewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Haven&apos;t Beaten Your Current Score.
        /// </summary>
        public static string Challenge3_NotBeat {
            get {
                return ResourceManager.GetString("Challenge3_NotBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post on my wall.
        /// </summary>
        public static string Challenge3_PostWallButton {
            get {
                return ResourceManager.GetString("Challenge3_PostWallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Challenge3_SendBtn {
            get {
                return ResourceManager.GetString("Challenge3_SendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string Challenge3_SmsSend {
            get {
                return ResourceManager.GetString("Challenge3_SmsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can You Play?.
        /// </summary>
        public static string Challenge3_Title {
            get {
                return ResourceManager.GetString("Challenge3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you need to shut up the dog as quickly as you can by pressing the red button. The dog will bark five times..
        /// </summary>
        public static string Challenge4_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge4_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you need to shut up the dog as quickly as you can by pressing the red button. The dog will bark three times..
        /// </summary>
        public static string Challenge4_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge4_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        public static string Challenge4_StartButton {
            get {
                return ResourceManager.GetString("Challenge4_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut up!.
        /// </summary>
        public static string Challenge4_StopButton {
            get {
                return ResourceManager.GetString("Challenge4_StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut the dog!.
        /// </summary>
        public static string Challenge4_Title {
            get {
                return ResourceManager.GetString("Challenge4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 5 Level 2.
        /// </summary>
        public static string Challenge5_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge5_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 5 Level 1.
        /// </summary>
        public static string Challenge5_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge5_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouncing Game!.
        /// </summary>
        public static string Challenge5_Title {
            get {
                return ResourceManager.GetString("Challenge5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to throw your cellphone as high as you can. Minimum you have to reach two meters..
        /// </summary>
        public static string Challenge6_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge6_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this challenge you have to throw your cellphone as high as you can. Minimum you have to reach one meter..
        /// </summary>
        public static string Challenge6_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge6_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Phone.
        /// </summary>
        public static string Challenge6_Title {
            get {
                return ResourceManager.GetString("Challenge6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 7 Level 2.
        /// </summary>
        public static string Challenge7_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge7_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 7 Level 1.
        /// </summary>
        public static string Challenge7_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge7_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch Me.
        /// </summary>
        public static string Challenge7_Title {
            get {
                return ResourceManager.GetString("Challenge7_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 8 Level 2.
        /// </summary>
        public static string Challenge8_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge8_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 8 Level 1.
        /// </summary>
        public static string Challenge8_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge8_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color &amp; Text.
        /// </summary>
        public static string Challenge8_Title {
            get {
                return ResourceManager.GetString("Challenge8_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 9 Level 2.
        /// </summary>
        public static string Challenge9_DescriptionHardTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge9_DescriptionHardTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 9 Level 1.
        /// </summary>
        public static string Challenge9_DescriptionTxtBlockText {
            get {
                return ResourceManager.GetString("Challenge9_DescriptionTxtBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Complete.
        /// </summary>
        public static string Challenge9_Title {
            get {
                return ResourceManager.GetString("Challenge9_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts:.
        /// </summary>
        public static string ChallengeDetail_AttemptsTxtBlockTitle {
            get {
                return ResourceManager.GetString("ChallengeDetail_AttemptsTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Score.
        /// </summary>
        public static string ChallengeDetail_BestScoreTxtBlockTitle {
            get {
                return ResourceManager.GetString("ChallengeDetail_BestScoreTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ChallengeDetail_DetailsTxtBlockTitle {
            get {
                return ResourceManager.GetString("ChallengeDetail_DetailsTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Score.
        /// </summary>
        public static string ChallengeDetail_LastScoreTxtBlockTitle {
            get {
                return ResourceManager.GetString("ChallengeDetail_LastScoreTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string ChallengeDetail_StartTimeTxtBlockTitle {
            get {
                return ResourceManager.GetString("ChallengeDetail_StartTimeTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        public static string HomePage_ChallengesPivotTitle {
            get {
                return ResourceManager.GetString("HomePage_ChallengesPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string HomePage_LogoutBtnTitle {
            get {
                return ResourceManager.GetString("HomePage_LogoutBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure?.
        /// </summary>
        public static string HomePage_LogoutMessage {
            get {
                return ResourceManager.GetString("HomePage_LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string HomePage_ProfilePivotTitle {
            get {
                return ResourceManager.GetString("HomePage_ProfilePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Has Occurred When Updating The Ranking.
        /// </summary>
        public static string HomePage_RankingError {
            get {
                return ResourceManager.GetString("HomePage_RankingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string HomePage_RankingPivotTitle {
            get {
                return ResourceManager.GetString("HomePage_RankingPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string HomePage_RetryBtnTitle {
            get {
                return ResourceManager.GetString("HomePage_RetryBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Has Occurred While Sending The Score.
        /// </summary>
        public static string HomePage_ScoreError {
            get {
                return ResourceManager.GetString("HomePage_ScoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Has Been Sent Successfully!.
        /// </summary>
        public static string HomePage_ScoreSuccess {
            get {
                return ResourceManager.GetString("HomePage_ScoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string HomePage_SettingsTxtBlockTitle {
            get {
                return ResourceManager.GetString("HomePage_SettingsTxtBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Has Occurred When Log In.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Facebook.
        /// </summary>
        public static string LoginPage_LoginBtnTitle {
            get {
                return ResourceManager.GetString("LoginPage_LoginBtnTitle", resourceCulture);
            }
        }
    }
}
